version: "3.9"
services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
volumes:
  postgres_db:

